#!/usr/bin/env python
# -*- coding: utf-8 -*-
from FlowCyPy import circuits, peak_locator, triggering_system
from FlowCyPy.digitizer import Digitizer
from FlowCyPy.signal_generator import SignalGenerator


class SignalProcessing:
    """
    Container for analog and digital signal processing stages in a simulated flow cytometry pipeline.

    This class orchestrates the application of analog electronic filtering, digitization, triggering,
    and peak detection algorithms. It integrates key building blocks of the signal acquisition chain
    in a modular and extensible way.

    Parameters
    ----------
    analog_processing : list of circuits.SignalProcessor
        List of analog signal processing components (e.g., amplifiers, filters) applied to
        simulated voltage traces before digitization.
    digitizer : Digitizer
        Digitization module that converts analog voltage signals to digital values using
        specified bit depth, voltage range, and sampling parameters.
    triggering_system : triggering_system.BaseTrigger
        Component responsible for extracting signal segments based on threshold-crossing
        or window-based logic applied to the analog signal.
    peak_algorithm : peak_locator.BasePeakLocator
        Peak detection algorithm that locates and characterizes peaks in the digitized signal
        (e.g., based on amplitude, area, or width).
    """

    def __init__(
        self,
        digitizer: Digitizer,
        analog_processing: list[circuits.SignalProcessor] = (),
        triggering_system: triggering_system.BaseTrigger = None,
        peak_algorithm: peak_locator.BasePeakLocator = None,
    ):
        self.analog_processing = analog_processing
        self.digitizer = digitizer
        self.triggering_system = triggering_system
        self.peak_algorithm = peak_algorithm

    def process_analog(self, signal_generator: SignalGenerator) -> None:
        """
        Applies analog signal processing to the input voltage signal.

        Each `circuits.SignalProcessor` module in the analog processing chain is applied sequentially
        to the raw analog voltage traces generated by the `SignalGenerator`, modifying the
        signal in-place.

        Parameters
        ----------
        signal_generator : SignalGenerator
            The generator that holds raw signal traces (in volts) to be processed by the analog circuitry.
        """
        for circuit in self.analog_processing:
            circuit.process(
                signal_generator=signal_generator,
                sampling_rate=self.digitizer.sampling_rate,
            )
