
from FlowCyPy import units
from FlowCyPy.circuits import SignalProcessor
from FlowCyPy.signal_digitizer import SignalDigitizer
from FlowCyPy.triggering_system import BaseTrigger
from FlowCyPy.peak_locator import BasePeakLocator
from FlowCyPy.signal_generator import SignalGenerator

class SignalProcessing:
    """
    Container for analog and digital signal processing stages in a simulated flow cytometry pipeline.

    This class orchestrates the application of analog electronic filtering, digitization, triggering,
    and peak detection algorithms. It integrates key building blocks of the signal acquisition chain
    in a modular and extensible way.

    Parameters
    ----------
    analog_processing : list of SignalProcessor
        List of analog signal processing components (e.g., amplifiers, filters) applied to
        simulated voltage traces before digitization.
    digitizer : SignalDigitizer
        Digitization module that converts analog voltage signals to digital values using
        specified bit depth, voltage range, and sampling parameters.
    triggering_system : BaseTrigger
        Component responsible for extracting signal segments based on threshold-crossing
        or window-based logic applied to the analog signal.
    peak_algorithm : BasePeakLocator
        Peak detection algorithm that locates and characterizes peaks in the digitized signal
        (e.g., based on amplitude, area, or width).
    """

    def __init__(self,
        analog_processing: list[SignalProcessor],
        digitizer: SignalDigitizer,
        triggering_system: BaseTrigger = None,
        peak_algorithm: BasePeakLocator = None):

        self.analog_processing = analog_processing
        self.digitizer = digitizer
        self.triggering_system = triggering_system
        self.peak_algorithm = peak_algorithm

    def process_analog(self, signal_generator: SignalGenerator):
        """
        Applies analog signal processing to the input voltage signal.

        Each `SignalProcessor` module in the analog processing chain is applied sequentially
        to the raw analog voltage traces generated by the `SignalGenerator`, modifying the
        signal in-place.

        Parameters
        ----------
        signal_generator : SignalGenerator
            The generator that holds raw signal traces (in volts) to be processed by the analog circuitry.
        """
        for circuit in self.analog_processing:
            circuit.process(
                signal_generator=signal_generator,
                sampling_rate=self.digitizer.sampling_rate
            )

    def process_digital(self, results: object) -> None:
        """
        Applies digitization and peak detection to the triggered analog signal.

        This method performs two key steps:
        1. Converts the triggered analog acquisition to a digital trace using the digitizer.
        2. If a peak detection algorithm is provided, applies it to the digital trace
           to extract peak-level metrics such as amplitude or area.

        The results are attached to the `results` object as:
        - `results.digital_acquisition`: digitized signal trace
        - `results.peaks`: dictionary or structured data representing peak features (optional)

        Parameters
        ----------
        results : object
            An object with a `triggered_analog_acquisition` attribute, expected to hold the
            analog signal segment previously extracted by the triggering system. The method
            attaches `digital_acquisition` and `peaks` attributes to this object.
        """
        results.triggered_digital = results.triggered_analog.digitalize(digitizer=self.digitizer)

        results.triggered_digital.normalize_units(signal_units=units.bit_bins)

        if self.peak_algorithm is not None:
            results.peaks = self.peak_algorithm.run(results.triggered_digital)

