name: Deploy

on:
    push:
        branches: [ "master" ]
        tags:
          - '*'
    pull_request:
        branches: [ "master" ]

permissions:
    contents: write

jobs:
    build_pure_python:
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_pure_python_package@master
            with:
                python-version: '3.10'

    publish_documentation:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        needs: [build_pure_python]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_documentation@master
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                package-name: FlowCytometry
                python-version: "3.10" #no documentation for python 3.7 (pickle5 not presentË˜)

    publish_wheel:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        needs: [build_pure_python, publish_documentation]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_pypi@master
            with:
                python-version: "3.10"
                password: ${{ secrets.PYPI_API_TOKEN }}
