name: Deploy Conda Packages

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read

jobs:
  linux:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_compiled_package_to_anaconda.yml@v2
    with:
      python_versions: '["3.11", "3.12", "3.13"]'
      apt_package: 'libfftw3-double3 libfftw3-dev'
      os_list: '["ubuntu-latest", "macos-latest"]'
      package_name: flowcypy
      recipe_path: conda.recipe
      test_import: FlowCyPy
    secrets:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
