name: Publish release

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read

jobs:
  release:
    uses: MartinPdeS/MPSActions/.github/workflows/publish_release.yml@v5
    with:
      pypi_python_version: "3.11"
      pypi_build_linux: true
      pypi_build_macos: true
      pypi_build_windows: false
      pypi_apt_package: libfftw3-double3 libfftw3-dev
      pypi_brew_package: fftw
      conda_python_versions: '["3.11", "3.12", "3.13"]'
      conda_os_list: '["ubuntu-latest", "macos-latest"]'
      conda_package_name: flowcypy
      conda_recipe_path: conda.recipe
      conda_test_import: FlowCyPy
      conda_apt_package: libfftw3-double3 libfftw3-dev
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
